"""Audited source/test ownership mappings; other actions retain native permissions.

Test commands below are documentation for the runner, never an allowlist.
Logic Gate Simulator remains excluded until its origin is available and audited.
"""

SKIPPED_REPOSITORIES = ('logic_gate_simulator',)

REPO_POLICIES = {'heybridge': {'schema_version': 2,
               'source_globs': ['lib/*.ex',
                                'lib/*.exs',
                                'lib/*.heex',
                                'lib/*.eex',
                                'lib/*.leex',
                                'config/*.exs',
                                'mix.exs',
                                'mix.lock',
                                '.formatter.exs',
                                '.credo.exs',
                                'assets/js/*.js',
                                'assets/js/*.mjs',
                                'assets/js/*.ts',
                                'assets/js/*.tsx',
                                'assets/css/*.css',
                                'assets/css/*.scss',
                                'assets/vendor/*.js',
                                'assets/vendor/*.ts',
                                'assets/package.json',
                                'assets/package-lock.json',
                                'assets/tsconfig.json',
                                'assets/vitest.config.mts',
                                'priv/repo/*.exs',
                                'rel/overlays/bin/server',
                                'rel/overlays/bin/server.bat',
                                'rel/overlays/bin/migrate',
                                'rel/overlays/bin/migrate.bat',
                                'infra/*.tf',
                                'infra/*.hcl',
                                'infra/*.yaml',
                                'infra/*.yml',
                                'deploy/*.sh',
                                'deploy/*.yaml',
                                'deploy/*.yml',
                                'deploy/*.tmpl',
                                'deploy/Caddyfile',
                                'Dockerfile',
                                '.github/workflows/*.yml',
                                '.github/workflows/*.yaml',
                                'priv/hey/*.py',
                                'scripts/*.py'],
               'test_globs': ['test/**',
                              '**/*_test.py',
                              '**/*.test.js',
                              '**/*.test.ts',
                              '**/*.spec.js',
                              '**/*.spec.ts']},
 'rode': {'schema_version': 2,
          'source_globs': ['lib/*.ex',
                           'lib/*.exs',
                           'lib/*.heex',
                           'lib/*.eex',
                           'lib/*.leex',
                           'config/*.exs',
                           'mix.exs',
                           'mix.lock',
                           '.formatter.exs',
                           '.credo.exs',
                           'assets/js/*.js',
                           'assets/js/*.mjs',
                           'assets/js/*.ts',
                           'assets/js/*.tsx',
                           'assets/css/*.css',
                           'assets/css/*.scss',
                           'assets/vendor/*.js',
                           'assets/vendor/*.ts',
                           'assets/package.json',
                           'assets/package-lock.json',
                           'assets/tsconfig.json',
                           'assets/vitest.config.mts',
                           'priv/repo/seeds.exs',
                           'priv/repo/pg_to_sqlite.exs',
                           'priv/repo/migrations/*.exs',
                           'rel/overlays/bin/server',
                           'rel/overlays/bin/seed',
                           'rel/overlays/bin/server.bat',
                           'rel/overlays/bin/migrate',
                           'rel/overlays/bin/migrate.bat',
                           'infra/*.tf',
                           'infra/*.hcl',
                           'infra/*.yaml',
                           'infra/*.yml',
                           'deploy/*.sh',
                           'deploy/*.yaml',
                           'deploy/*.yml',
                           'deploy/*.tmpl',
                           'deploy/Caddyfile',
                           'Dockerfile',
                           '.github/workflows/*.yml',
                           '.github/workflows/*.yaml'],
          'test_globs': ['test/**',
                         '**/*_test.py',
                         '**/*.test.js',
                         '**/*.test.ts',
                         '**/*.spec.js',
                         '**/*.spec.ts']},
 'workout': {'schema_version': 2,
             'source_globs': ['lib/*.ex',
                              'lib/*.exs',
                              'lib/*.heex',
                              'lib/*.eex',
                              'lib/*.leex',
                              'config/*.exs',
                              'mix.exs',
                              'mix.lock',
                              '.formatter.exs',
                              '.credo.exs',
                              'assets/js/*.js',
                              'assets/js/*.mjs',
                              'assets/js/*.ts',
                              'assets/js/*.tsx',
                              'assets/css/*.css',
                              'assets/css/*.scss',
                              'assets/vendor/*.js',
                              'assets/vendor/*.ts',
                              'assets/package.json',
                              'assets/package-lock.json',
                              'assets/tsconfig.json',
                              'assets/vitest.config.mts',
                              'priv/repo/*.exs',
                              'rel/overlays/bin/server',
                              'rel/overlays/bin/server.bat',
                              'rel/overlays/bin/migrate',
                              'rel/overlays/bin/migrate.bat',
                              'infra/*.tf',
                              'infra/*.hcl',
                              'infra/*.yaml',
                              'infra/*.yml',
                              'deploy/*.sh',
                              'deploy/*.yaml',
                              'deploy/*.yml',
                              'deploy/*.tmpl',
                              'deploy/Caddyfile',
                              'Dockerfile',
                              '.github/workflows/*.yml',
                              '.github/workflows/*.yaml'],
             'test_globs': ['test/**',
                            '**/*_test.py',
                            '**/*.test.js',
                            '**/*.test.ts',
                            '**/*.spec.js',
                            '**/*.spec.ts']},
 'marquee': {'schema_version': 2,
             'source_globs': ['lib/*.ex',
                              'lib/*.exs',
                              'lib/*.heex',
                              'lib/*.eex',
                              'lib/*.leex',
                              'config/*.exs',
                              'mix.exs',
                              'mix.lock',
                              '.formatter.exs',
                              '.credo.exs',
                              'assets/js/*.js',
                              'assets/js/*.mjs',
                              'assets/js/*.ts',
                              'assets/js/*.tsx',
                              'assets/css/*.css',
                              'assets/css/*.scss',
                              'assets/vendor/*.js',
                              'assets/vendor/*.ts',
                              'assets/package.json',
                              'assets/package-lock.json',
                              'assets/tsconfig.json',
                              'assets/vitest.config.mts',
                              'priv/repo/*.exs',
                              'rel/overlays/bin/server',
                              'rel/env.sh.eex',
                              '.githooks/pre-commit',
                              'rel/overlays/bin/server.bat',
                              'rel/overlays/bin/migrate',
                              'rel/overlays/bin/migrate.bat',
                              'infra/*.tf',
                              'infra/*.hcl',
                              'infra/*.yaml',
                              'infra/*.yml',
                              'deploy/*.sh',
                              'deploy/*.yaml',
                              'deploy/*.yml',
                              'deploy/*.tmpl',
                              'deploy/Caddyfile',
                              'Dockerfile',
                              '.github/workflows/*.yml',
                              '.github/workflows/*.yaml'],
             'test_globs': ['test/**',
                            'features/**',
                            'assets/test/**',
                            '**/*_test.py',
                            '**/*.test.js',
                            '**/*.test.ts',
                            '**/*.spec.js',
                            '**/*.spec.ts']},
 'residency-schedule': {'schema_version': 2,
                        'source_globs': ['lib/*.ex',
                                         'lib/*.exs',
                                         'lib/*.heex',
                                         'lib/*.eex',
                                         'lib/*.leex',
                                         'config/*.exs',
                                         'mix.exs',
                                         'mix.lock',
                                         '.formatter.exs',
                                         '.credo.exs',
                                         'assets/js/*.js',
                                         'assets/js/*.mjs',
                                         'assets/js/*.ts',
                                         'assets/js/*.tsx',
                                         'assets/css/*.css',
                                         'assets/css/*.scss',
                                         'assets/vendor/*.js',
                                         'assets/vendor/*.ts',
                                         'assets/package.json',
                                         'assets/package-lock.json',
                                         'assets/tsconfig.json',
                                         'assets/vitest.config.mts',
                                         'priv/repo/*.exs',
                                         'rel/overlays/bin/server',
                                         'rel/overlays/bin/server.bat',
                                         'rel/overlays/bin/migrate',
                                         'rel/overlays/bin/migrate.bat',
                                         'infra/*.tf',
                                         'infra/*.hcl',
                                         'infra/*.yaml',
                                         'infra/*.yml',
                                         'deploy/*.sh',
                                         'deploy/*.yaml',
                                         'deploy/*.yml',
                                         'deploy/*.tmpl',
                                         'deploy/Caddyfile',
                                         'Dockerfile',
                                         '.github/workflows/*.yml',
                                         '.github/workflows/*.yaml',
                                         'priv/demo/*.py',
                                         'priv/demo/*.sh'],
                        'test_globs': ['test/**',
                                       '**/*_test.py',
                                       '**/*.test.js',
                                       '**/*.test.ts',
                                       '**/*.spec.js',
                                       '**/*.spec.ts']},
 'otlp_shipper': {'schema_version': 2,
                  'source_globs': ['lib/*.ex',
                                   'lib/*.exs',
                                   'config/*.exs',
                                   'mix/*.exs',
                                   'mix/*.ex',
                                   'mix.exs',
                                   'mix.lock',
                                   '.formatter.exs',
                                   '.credo.exs',
                                   'scripts/*.sh',
                                   'scripts/*.py',
                                   'priv/proto/*.proto',
                                   'priv/conformance/*.exs',
                                   'priv/conformance/*.yaml',
                                   '.github/workflows/*.yml',
                                   '.github/workflows/*.yaml'],
                  'test_globs': ['test/**',
                                 'features/**',
                                 'scripts/test_agent_guard*.py',
                                 'scripts/fixtures/trace_replacement/**',
                                 '**/*_test.py',
                                 '**/*.test.js',
                                 '**/*.test.ts',
                                 '**/*.spec.js',
                                 '**/*.spec.ts'],
                  'legacy_commands': ['/usr/bin/python3 "$(git rev-parse '
                                      '--show-toplevel)/.codex/hooks/run_guard.py"']},
 'page_monitor': {'schema_version': 2,
                  'source_globs': ['src/*.js',
                                   'src/*.mjs',
                                   'src/*.ts',
                                   'src/*.tsx',
                                   'src/*.jsx',
                                   'src/*.css',
                                   'src/*.scss',
                                   'src/*.html',
                                   'scripts/*.mjs',
                                   'scripts/*.js',
                                   'scripts/*.ts',
                                   'package.json',
                                   'package-lock.json',
                                   'tsconfig.json',
                                   'vite.config.ts',
                                   'vitest.config.ts',
                                   'playwright.config.ts',
                                   'eslint.config.js',
                                   'release-config.ts',
                                   'release.config.json',
                                   'public/manifest.json',
                                   'offscreen.html',
                                   'sidepanel.html'],
                  'test_globs': ['tests/**',
                                 '**/*_test.py',
                                 '**/*.test.js',
                                 '**/*.test.ts',
                                 '**/*.spec.js',
                                 '**/*.spec.ts',
                                 'scripts/test-*.mjs']},
 'live-view-connection-monitor': {'schema_version': 2,
                                  'source_globs': ['src/*.js',
                                                   'src/*.mjs',
                                                   'src/*.ts',
                                                   'src/*.tsx',
                                                   'src/*.jsx',
                                                   'src/*.css',
                                                   'src/*.scss',
                                                   'src/*.html',
                                                   'scripts/*.mjs',
                                                   'scripts/*.js',
                                                   'scripts/*.ts',
                                                   'package.json',
                                                   'package-lock.json',
                                                   'tsconfig.json',
                                                   'vite.config.ts',
                                                   'vitest.config.ts',
                                                   'playwright.config.ts',
                                                   'eslint.config.js',
                                                   'release-config.ts',
                                                   'release.config.json',
                                                   'public/manifest.json',
                                                   'devtools.html',
                                                   'panel.html',
                                                   'popup.html'],
                                  'test_globs': ['tests/**',
                                                 '**/*_test.py',
                                                 '**/*.test.js',
                                                 '**/*.test.ts',
                                                 '**/*.spec.js',
                                                 '**/*.spec.ts',
                                                 'scripts/test-*.mjs']},
 'cookie_clear_on_tab_close': {'schema_version': 2,
                               'source_globs': ['src/*.js',
                                                'src/*.mjs',
                                                'src/*.ts',
                                                'src/*.tsx',
                                                'src/*.jsx',
                                                'src/*.css',
                                                'src/*.scss',
                                                'src/*.html',
                                                'scripts/*.mjs',
                                                'scripts/*.js',
                                                'scripts/*.ts',
                                                'package.json',
                                                'package-lock.json',
                                                'tsconfig.json',
                                                'vite.config.ts',
                                                'vitest.config.ts',
                                                'playwright.config.ts',
                                                'eslint.config.js',
                                                'release-config.ts',
                                                'release.config.json',
                                                'public/manifest.json',
                                                'panel.html'],
                               'test_globs': ['tests/**',
                                              '**/*_test.py',
                                              '**/*.test.js',
                                              '**/*.test.ts',
                                              '**/*.spec.js',
                                              '**/*.spec.ts',
                                              'scripts/test-*.mjs']},
 'consensus': {'schema_version': 2,
               'source_globs': ['app/*.rb',
                                'lib/*.rb',
                                'views/*.erb',
                                'views/*.haml',
                                'views/*.slim',
                                'config/*.rb',
                                'db/migrate/*.rb',
                                'db/seed-data/*.rb',
                                'public/js/*.js',
                                'public/js/*.mjs',
                                'public/js/*.ts',
                                'public/css/*.css',
                                'public/css/*.scss',
                                'scripts/*.sh',
                                'scripts/*.rb',
                                'app.rb',
                                'config.ru',
                                'Gemfile',
                                'Gemfile.lock',
                                'Rakefile',
                                '.rubocop.yml',
                                'infra/*.tf',
                                'infra/*.hcl',
                                'infra/*.yaml',
                                'infra/*.yml',
                                'deploy/*.sh',
                                'deploy/*.yaml',
                                'deploy/*.yml',
                                'deploy/*.tmpl',
                                'deploy/Caddyfile',
                                'Dockerfile',
                                '.github/workflows/*.yml',
                                '.github/workflows/*.yaml',
                                'bin/vendor-biometry',
                                'vendor/biometry/lib/*.rb',
                                'vendor/biometry/biometry.gemspec',
                                'vendor/biometry/exe/biometry'],
               'test_globs': ['spec/**',
                              '**/*_test.py',
                              '**/*.test.js',
                              '**/*.test.ts',
                              '**/*.spec.js',
                              '**/*.spec.ts'],
               'legacy_commands': ['./scripts/protect-tests.sh', './scripts/gate.sh']},
 'football_supporters': {'schema_version': 2,
                         'source_globs': ['app/*.rb',
                                          'lib/*.rb',
                                          'views/*.erb',
                                          'views/*.haml',
                                          'views/*.slim',
                                          'config/*.rb',
                                          'db/migrate/*.rb',
                                          'db/seed-data/*.rb',
                                          'public/js/*.js',
                                          'public/js/*.mjs',
                                          'public/js/*.ts',
                                          'public/css/*.css',
                                          'public/css/*.scss',
                                          'scripts/*.sh',
                                          'scripts/*.rb',
                                          'app.rb',
                                          'config.ru',
                                          'Gemfile',
                                          'Gemfile.lock',
                                          'Rakefile',
                                          '.rubocop.yml',
                                          'infra/*.tf',
                                          'infra/*.hcl',
                                          'infra/*.yaml',
                                          'infra/*.yml',
                                          'deploy/*.sh',
                                          'deploy/*.yaml',
                                          'deploy/*.yml',
                                          'deploy/*.tmpl',
                                          'deploy/Caddyfile',
                                          'Dockerfile',
                                          '.github/workflows/*.yml',
                                          '.github/workflows/*.yaml',
                                          'bin/mcp'],
                         'test_globs': ['spec/**',
                                        '**/*_test.py',
                                        '**/*.test.js',
                                        '**/*.test.ts',
                                        '**/*.spec.js',
                                        '**/*.spec.ts']},
 'biometry': {'schema_version': 2,
              'source_globs': ['lib/*.rb',
                               'scripts/*.rb',
                               'scripts/*.sh',
                               'Gemfile',
                               'Gemfile.lock',
                               'Rakefile',
                               'biometry.gemspec',
                               '.rubocop.yml',
                               'exe/biometry'],
              'test_globs': ['spec/**',
                             'scripts/fixtures/**',
                             '**/*_test.py',
                             '**/*.test.js',
                             '**/*.test.ts',
                             '**/*.spec.js',
                             '**/*.spec.ts'],
              'legacy_commands': ['./scripts/protect-tests.sh', './scripts/gate.sh']},
 'push-button-deploy': {'schema_version': 2,
                        'source_globs': ['bootstrap.sh',
                                         'bootstrap-gitea.sh',
                                         'teardown.sh',
                                         'teardown-gitea.sh',
                                         'claude-docs.sh',
                                         'agent-docs.sh',
                                         'scripts/*.sh',
                                         'scripts/agent-workflow/*.py',
                                         'deploy/*.sh',
                                         'deploy/*.yaml',
                                         'deploy/*.yml',
                                         'deploy/*.tmpl',
                                         'deploy/Caddyfile',
                                         'app/Dockerfile',
                                         'app/Dockerfile.ruby',
                                         'app/.dockerignore',
                                         'app/.dockerignore.ruby',
                                         'app/.github/workflows/*.yml',
                                         'app/.gitea/workflows/*.yml',
                                         '.github/workflows/*.yml',
                                         'infra-app/*.tf',
                                         'infra-app/*.hcl',
                                         'infra-app/*.yaml',
                                         'infra-app/*.yml',
                                         'infra-gitea/*.tf',
                                         'infra-gitea/*.hcl',
                                         'infra-gitea/*.yaml',
                                         'infra-gitea/*.yml',
                                         'infra-persistent/*.tf',
                                         'infra-persistent/*.hcl',
                                         'infra-persistent/*.yaml',
                                         'infra-persistent/*.yml',
                                         'infra-state/*.tf',
                                         'infra-state/*.hcl',
                                         'infra-state/*.yaml',
                                         'infra-state/*.yml',
                                         'infra-tenant/*.tf',
                                         'infra-tenant/*.hcl',
                                         'infra-tenant/*.yaml',
                                         'infra-tenant/*.yml',
                                         'gitea-host/*.yaml',
                                         'gitea-host/*.yml',
                                         'app-template/.claude/cloud-setup.sh',
                                         'app-template/.claude/settings.json',
                                         'app-template/.claude/settings.format-hook.json',
                                         'app-template-ruby/.claude/cloud-setup.sh',
                                         'app-template-ruby/.claude/settings.json',
                                         'app-template-ruby/.claude/settings.format-hook.json'],
                        'test_globs': ['test/**',
                                       '**/*_test.py',
                                       '**/*.test.js',
                                       '**/*.test.ts',
                                       '**/*.spec.js',
                                       '**/*.spec.ts']}}

RECOMMENDED_TEST_COMMANDS = {'heybridge': [['mix', 'test'],
               ['mix', 'format', '--check-formatted'],
               ['mix', 'compile', '--warnings-as-errors']],
 'rode': [['mix', 'test'],
          ['mix', 'format', '--check-formatted'],
          ['mix', 'compile', '--warnings-as-errors']],
 'workout': [['mix', 'test'],
             ['mix', 'format', '--check-formatted'],
             ['mix', 'compile', '--warnings-as-errors'],
             ['mix', 'credo', '--strict'],
             ['mix', 'test.e2e']],
 'marquee': [['mix', 'test'],
             ['mix', 'format', '--check-formatted'],
             ['mix', 'compile', '--warnings-as-errors'],
             ['mix', 'coveralls', '--exclude', 'e2e'],
             ['mix', 'test', '--only', 'e2e'],
             ['npm', 'test', '--prefix', 'assets'],
             ['npm', 'run', 'typecheck', '--prefix', 'assets'],
             ['npm', 'run', 'test:coverage', '--prefix', 'assets'],
             ['env', 'MIX_ENV=test', 'mix', 'marquee.cucumber']],
 'residency-schedule': [['mix', 'test'],
                        ['mix', 'format', '--check-formatted'],
                        ['mix', 'compile', '--warnings-as-errors']],
 'otlp_shipper': [['mix', 'test'],
                  ['mix', 'format', '--check-formatted'],
                  ['mix', 'compile', '--warnings-as-errors'],
                  ['mix', 'credo', '--strict'],
                  ['mix', 'dialyzer'],
                  ['python3',
                   '-m',
                   'unittest',
                   'discover',
                   '-s',
                   'scripts',
                   '-p',
                   'test_agent_guard*.py'],
                  ['env', 'MIX_ENV=test', 'mix', 'cucumber']],
 'page_monitor': [['npm', 'test'],
                  ['npm', 'run', 'verify'],
                  ['npm', 'run', 'typecheck'],
                  ['npm', 'run', 'lint'],
                  ['npm', 'run', 'format:check'],
                  ['npm', 'run', 'test:e2e'],
                  ['npm', 'run', 'test:e2e:firefox']],
 'live-view-connection-monitor': [['npm', 'test'],
                                  ['npm', 'run', 'verify'],
                                  ['npm', 'run', 'typecheck'],
                                  ['npm', 'run', 'lint'],
                                  ['npm', 'run', 'format:check'],
                                  ['npm', 'run', 'test:e2e'],
                                  ['npm', 'run', 'test:e2e:firefox']],
 'cookie_clear_on_tab_close': [['npm', 'test'],
                               ['npm', 'run', 'verify'],
                               ['npm', 'run', 'typecheck'],
                               ['npm', 'run', 'lint'],
                               ['npm', 'run', 'format:check'],
                               ['npm', 'run', 'test:e2e'],
                               ['npm', 'run', 'test:e2e:firefox'],
                               ['npm', 'run', 'test:behavior']],
 'consensus': [['bundle', 'exec', 'rspec'], ['bundle', 'exec', 'rake', 'spec']],
 'football_supporters': [['bundle', 'exec', 'rspec'], ['bundle', 'exec', 'rake', 'spec']],
 'biometry': [['bundle', 'exec', 'rake', 'spec'], ['bundle', 'exec', 'rake', 'verify']],
 'push-button-deploy': [['bash', 'test/run.sh']]}

NOTES = {
    'heybridge': 'Preserve existing bootstrap setup and HEY privacy guidance.',
    'push-button-deploy': 'Shipped app template code is product source; root agent instructions remain unscoped.',
    'marquee': 'Git pre-commit may format code and stage files. Review its diff and accepted-test hashes; no delivery hook gate is added.',
    'biometry': 'Existing privacy and clinical oracle guidance remains applicable; data is not an edit-hook category.',
    'residency-schedule': 'Preserve existing PII guidance and PostgreSQL setup; no delivery hook gate is added.',
}
